# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 92c4c305418de033257529b763e7d0d4adb02eed0167e2879b5e9e162ce9d32a3c40ee088c81115959640efbc9b327f9df95bc2a40db03780223ac6a1799ea49
  google_places_api_key: AIzaSyBqIHyjvRNvoAojiwKptuQqca-epvDrMyk
  google_storage_access_key_id: lala
  google_storage_secret_access_key: lolo

staging:
  secret_key_base: 92c4c305418de033257529b763e7d0d4adb02eed0167e2879b5e9e162ce9d32a3c40ee088c81115959640efbc9b327f9df95bc2a40db03780223ac6a1799ea49
  google_places_api_key: AIzaSyBqIHyjvRNvoAojiwKptuQqca-epvDrMyk
  google_storage_access_key_id: lala
  google_storage_secret_access_key: lolo
  gmail_username: <%= ENV["GMAIL_USERNAME"] %>
  gmail_password: <%= ENV["GMAIL_PASSWORD"] %>

test:
  secret_key_base: d637c958823c78ec45d71c0eed26fa041ec523449f8cf0d1daaa035bec528e4cae71e6afed579cb9dbaaa51b77826f17aa2867cef805292d84f7f8402e98ceb4
  google_places_api_key: AIzaSyBqIHyjvRNvoAojiwKptuQqca-epvDrMyk

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  google_places_api_key: <%= ENV["GOOGLE_PLACES_KEY"] %>
  google_storage_access_key_id: <%= ENV["GOOGLE_STORAGE_ID"] %>
  google_storage_secret_access_key: <%= ENV["GOOGLE_STORAGE_ACCESS_KEY"] %>